machine:
  environment:
    CIRCLE_BUILD_DIR: $HOME/$CIRCLE_PROJECT_REPONAME
    PATH: $PATH:$CIRCLE_BUILD_DIR/bin:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"

  post:
    - mkdir -p $CIRCLE_BUILD_DIR/bin
  node:
    version: 8.9.1

dependencies:
  pre:
    - go get -v github.com/bep/s3deploy
  override:
    - npm
  cache_directories:
    - ~/.cache/npm
    - bin

test:
  override
    - npm run build

deployment:
  s3up:
    branch: develop
    commands:
      - s3deploy -source=dist/ -region=ap-southeast-1 -bucket=vuejs-ci-cd-aws